### ISSUE TITLE
As an user, I want to order through a text box so that I can order my drinks exactly

### ISSUE THREAD

**Issue by duongnd99** [DuongNguyen99/USTH-SE-2019#10]
**GUI presentation**
- [x] Optimize the background and colors.
- [x] Centralize all.

**High-level design**
- [x] Apply INVEST rule to user story.
- [x] Learn basic knowledge about HTML and CSS.
- [ ] Apply APIs to the code.

**Low-level design**
- [x] Choose design pattern.
- [ ] Implementation
  
**Testing**
- [ ] Make sure the coverage is more than 80%.
- [ ] Make GUI test cases.
- Design black box test cases.
   - [ ] Test the response when texting information
   - [ ] Test the response when sending information.
- [ ] Analyze the results of testing and offer the solution.

**Comment by ngocdo4299** [comment]
Unable to delivery this feature at the moment

**Comment by ngocdo4299** [comment]
Response sheet
https://docs.google.com/spreadsheets/d/1y3LBqUiE3lD0p_CG2i27-8vLo5oQ70833LA1HNccTwQ/edit#gid=0
